---
global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'grafana'
    scrape_interval: 5s
    dns_sd_configs:
    static_configs:
      - targets: ['grafana:3000']
  - job_name: 'promtail'
    scrape_interval: 5s
    dns_sd_configs:
    static_configs:
      - targets: ['promtail:9080']
  - job_name: 'demo-server'
    scrape_interval: 5s
    dns_sd_configs:
      - names:
          - 'server'
        type: 'A'
        port: 5000
