INVENTORY = [
    {
        "name": "They're Playing Our Song #269",
        "brewery": "Beerbliotek",
        "year": 2019,
        "abv": 7.5,
        "style": "New England IPA",
        "size": 330,
        "drunk": True,
        "stock": 0,
        "purchased": 1,
        "collaborators": ["Finback"],
        "barrel-aged": False,
    },
    {
        "name": "I'm So Aware This Is Happening #262",
        "brewery": "Beerbliotek",
        "year": 2019,
        "abv": 7.9,
        "style": "Imperial IPA",
        "size": 330,
        "drunk": True,
        "stock": 0,
        "purchased": 1,
        "barrel-aged": False,
    },
    {
        "name": "Jambe-de-Bois",
        "brewery": "Brasserie de la Senne",
        "year": 2019,
        "abv": 8,
        "style": "Belgian Tripple",
        "size": 330,
        "drunk": True,
        "stock": 0,
        "purchased": 1,
        "ibu": 49,
        "barrel-aged": False,
    },
    {
        "name": "Pere Noel",
        "brewery": "Brouwerij De Ranke",
        "year": 2018,
        "abv": 7,
        "style": "Christmas Ale",
        "size": 330,
        "drunk": True,
        "stock": 1,
        "purchased": 1,
        "barrel-aged": False,
    },
    {
        "name": "Delta IPA",
        "brewery": "Brussels Beer Project",
        "year": 2019,
        "abv": 6.5,
        "style": "Saison IPA",
        "size": 330,
        "drunk": True,
        "stock": 0,
        "purchased": 1,
        "ibu": 45,
        "barrel-aged": False,
    },
    {
        "name": "Rose de Gambrinus",
        "brewery": "Cantillon",
        "year": 2018,
        "abv": 5,
        "style": "Lambic - Framboise",
        "size": 750,
        "drunk": True,
        "stock": 1,
        "purchased": 1,
        "barrel-aged": False,
    },
    {
        "name": "Classic Gueuze",
        "brewery": "Cantillon",
        "year": 2018,
        "abv": 5,
        "style": "Gueuze Lambic",
        "size": 1500,
        "drunk": True,
        "stock": 0,
        "purchased": 1,
        "barrel-aged": False,
    },
    {
        "name": "A Fire by the Bines",
        "brewery": "Cloudwater",
        "year": 2019,
        "abv": 8,
        "style": "Double IPA",
        "size": 440,
        "drunk": False,
        "stock": 1,
        "purchased": 1,
        "barrel-aged": False,
    },
    {
        "name": "What's Best For Us, Is Also What's Best For You",
        "brewery": "Cloudwater",
        "year": 2019,
        "abv": 9,
        "style": "Double IPA",
        "size": 440,
        "drunk": True,
        "stock": 1,
        "purchased": 2,
        "barrel-aged": False,
    },
    {
        "name": "The Infinite Sides of the Globe",
        "brewery": "Cloudwater",
        "year": 2019,
        "abv": 5.5,
        "style": "Double Dry Hopped Pale Ale",
        "size": 440,
        "drunk": True,
        "stock": 0,
        "purchased": 1,
        "barrel-aged": False,
    },
    {
        "name": "An Ever Flowing Body Of Water",
        "brewery": "Cloudwater",
        "year": 2019,
        "abv": 6.7,
        "style": "IPA",
        "size": 440,
        "drunk": True,
        "stock": 0,
        "purchased": 1,
        "barrel-aged": False,
    },
    {
        "name": "Commander Reserve",
        "brewery": "Dead Frog",
        "year": 2015,
        "abv": 10.5,
        "style": "Imperial Stout",
        "size": 650,
        "drunk": False,
        "stock": 1,
        "purchased": 1,
        "barrel-aged": True,
    },
    {
        "name": "Argentum",
        "brewery": "Delirium",
        "year": 2018,
        "abv": 7,
        "style": "Hopped Amber Ale",
        "size": 330,
        "drunk": True,
        "stock": 0,
        "purchased": 1,
        "barrel-aged": False,
    },
    {
        "name": "The Dissident",
        "brewery": "Deschutes",
        "year": 2017,
        "abv": 10.5,
        "style": "Ale",
        "size": 650,
        "drunk": False,
        "stock": 1,
        "purchased": 1,
        "barrel-aged": True,
        "barrel-type": "Oak",
        "brewed-with": "cherries",
    },
    {
        "name": "Contains Nuts",
        "brewery": "Dot Brew",
        "year": 2019,
        "abv": 10.9,
        "style": "Imperial Milk Stout/Barrel Aged Porter",
        "size": 330,
        "drunk": False,
        "stock": 1,
        "purchased": 1,
        "barrel-aged": True,
    },
    {
        "name": "DOT 12",
        "brewery": "Dot Brew",
        "year": 2019,
        "abv": 9,
        "style": "Imperial Rye",
        "size": 330,
        "drunk": False,
        "stock": 1,
        "purchased": 1,
        "collaborators": ["12 acres"],
        "barrel-aged": True,
    },
    {
        "name": "Maroon Ball 7",
        "brewery": "Eight Degrees",
        "year": 2019,
        "abv": 8.3,
        "style": "kviek Double IPA",
        "size": 440,
        "drunk": True,
        "stock": 0,
        "purchased": 1,
        "barrel-aged": False,
    },
    {
        "name": "Helldorado",
        "brewery": "Firestone Walker",
        "year": 2016,
        "abv": 11.8,
        "style": "Blonde Barley Wine Ale",
        "size": 650,
        "drunk": False,
        "stock": 1,
        "purchased": 1,
        "barrel-aged": False,
    },
    {
        "name": "Stickee Monkee",
        "brewery": "Firestone Walker",
        "year": 2016,
        "abv": 11.6,
        "style": "Central Coast Quad",
        "size": 650,
        "drunk": False,
        "stock": 1,
        "purchased": 1,
        "barrel-aged": True,
    },
    {
        "name": "KBS ",
        "brewery": "Founders",
        "year": 2019,
        "abv": 12.2,
        "style": "Imperial Stout",
        "size": 355,
        "drunk": True,
        "stock": 1,
        "purchased": 1,
        "barrel-aged": True,
    },
    {
        "name": "CBS",
        "brewery": "Founders",
        "year": 2018,
        "abv": 11.6,
        "style": "Imperial Stout",
        "size": 355,
        "drunk": True,
        "stock": 1,
        "purchased": 1,
        "barrel-aged": True,
    },
    {
        "name": "Diving Bell",
        "brewery": "Galway Bay",
        "year": 2018,
        "abv": 9.5,
        "style": "Wee heavy",
        "size": 500,
        "drunk": True,
        "stock": 2,
        "purchased": 2,
        "barrel-aged": False,
    },
    {
        "name": "Two Hundred Fathoms",
        "brewery": "Galway Bay",
        "year": 2018,
        "abv": 10,
        "style": "Imperial Stout",
        "size": 500,
        "drunk": True,
        "stock": 3,
        "purchased": 3,
        "barrel-aged": True,
        "barrel-type": "Whiskey",
    },
    {
        "name": "Two Hundred Fathoms",
        "brewery": "Galway Bay",
        "year": 2017,
        "abv": 10,
        "style": "Imperial Stout",
        "size": 500,
        "drunk": True,
        "stock": 1,
        "purchased": 1,
        "barrel-aged": True,
        "barrel-type": "Whiskey",
    },
    {
        "name": "Harmonic Convergence",
        "brewery": "Galway Bay",
        "year": 2018,
        "abv": 12,
        "style": "Barley Wine",
        "size": 500,
        "drunk": False,
        "stock": 1,
        "purchased": 1,
        "ibu": 0,
        "collaborators": ["Boundary"],
        "barrel-aged": True,
    },
    {
        "name": "Harmonic Convergence",
        "brewery": "Galway Bay",
        "year": 2019,
        "abv": 10.5,
        "style": "Barley Wine",
        "size": 500,
        "drunk": False,
        "stock": 3,
        "purchased": 3,
        "collaborators": ["Boundary"],
        "barrel-aged": True,
        "barrel-type": "Sherry/Vermouth",
    },
    {
        "name": "Oata",
        "brewery": "Garage Beer co.",
        "year": 2019,
        "abv": 5.4,
        "style": "IPA",
        "size": 440,
        "drunk": True,
        "stock": 0,
        "purchased": 1,
        "barrel-aged": False,
    },
    {
        "name": "False Coloured Eyes",
        "brewery": "Garage Beer co.",
        "year": 2019,
        "abv": 6,
        "style": "New England IPA",
        "size": 440,
        "drunk": False,
        "stock": 1,
        "purchased": 1,
        "collaborators": ["Deya"],
        "barrel-aged": False,
    },
    {
        "name": "Supercombi",
        "brewery": "Garage Beer co.",
        "year": 2019,
        "abv": 8.6,
        "style": "Double IPA",
        "size": 440,
        "drunk": False,
        "stock": 1,
        "purchased": 1,
        "collaborators": ["Other Half", "Burial Beer"],
        "barrel-aged": False,
    },
    {
        "name": "Cotorres",
        "brewery": "Garage Beer co.",
        "year": 2019,
        "abv": 5.5,
        "style": "Berliner Weisse",
        "size": 440,
        "drunk": False,
        "stock": 1,
        "purchased": 1,
        "collaborators": ["Alvarado Street"],
        "barrel-aged": False,
    },
    {
        "name": "Winter Season",
        "brewery": "Hope",
        "year": 2019,
        "abv": 4.9,
        "style": "Black IPA",
        "size": 440,
        "drunk": True,
        "stock": 0,
        "purchased": 1,
        "ibu": 30,
        "barrel-aged": False,
    },
    {
        "name": "Great news ",
        "brewery": "Hopewell",
        "year": 2019,
        "abv": 5.6,
        "style": "Saison",
        "size": 475,
        "drunk": False,
        "stock": 1,
        "purchased": 1,
        "barrel-aged": False,
    },
    {
        "name": "Noire du Midi",
        "brewery": "L'Ermitage",
        "year": 2019,
        "abv": 6.9,
        "style": "Hoppy Porter",
        "size": 330,
        "drunk": True,
        "stock": 0,
        "purchased": 1,
        "barrel-aged": False,
    },
    {
        "name": "Tongerlo",
        "brewery": "Lux",
        "year": 2018,
        "abv": 6,
        "style": "Belgian Blond",
        "size": 750,
        "drunk": False,
        "stock": 1,
        "purchased": 1,
        "barrel-aged": False,
    },
    {
        "name": "Cryoflayer 8.88",
        "brewery": "Marz community Brewing Co.",
        "year": 2019,
        "abv": 8.88,
        "style": "Triple dry hopped hazy double IPA",
        "size": 330,
        "drunk": True,
        "stock": 1,
        "purchased": 4,
        "barrel-aged": False,
    },
    {
        "name": "Thomas Hardy's Ale",
        "brewery": "Meantime Brewing Company",
        "year": 2014,
        "abv": 11.7,
        "style": "Barley Wine",
        "size": 330,
        "drunk": False,
        "stock": 1,
        "purchased": 1,
        "barrel-aged": False,
    },
    {
        "name": "Monster Park (Mexican Hot Choclate Edition)",
        "brewery": "Modern Times",
        "year": 2019,
        "abv": 14.2,
        "style": "Imperial Stout",
        "size": 350,
        "drunk": False,
        "stock": 1,
        "purchased": 1,
        "barrel-aged": True,
        "barrel-type": "Bourbon",
    },
    {
        "name": "Mythic Worlds",
        "brewery": "Modern Times",
        "year": 2019,
        "abv": 7.6,
        "style": "New England IPA",
        "size": 440,
        "drunk": True,
        "stock": 0,
        "purchased": 1,
        "barrel-aged": False,
    },
    {
        "name": "Star City",
        "brewery": "Mothership",
        "year": 2019,
        "abv": 7.4,
        "style": "Double IPA",
        "size": 440,
        "drunk": True,
        "stock": 0,
        "purchased": 1,
        "ibu": 65,
        "collaborators": ["Fourpure Brewing co"],
        "barrel-aged": False,
    },
    {
        "name": "Leann Follain",
        "brewery": "O'hara's",
        "year": 2018,
        "abv": 8.1,
        "style": "Stout",
        "size": 750,
        "drunk": False,
        "stock": 1,
        "purchased": 1,
        "barrel-aged": True,
        "barrel-type": "Bourbon",
    },
    {
        "name": "Original Chocolate Ice Cream",
        "brewery": "Omnipollo",
        "year": 2019,
        "abv": 6.2,
        "style": "Brown Ale",
        "size": 440,
        "drunk": False,
        "stock": 1,
        "purchased": 1,
        "collaborators": ["Buxton"],
        "barrel-aged": False,
    },
    {
        "name": "Aon Pecan Mud Cake",
        "brewery": "Omnipollo",
        "year": 2019,
        "abv": 11,
        "style": "Imperial Stout",
        "size": 330,
        "drunk": True,
        "stock": 1,
        "purchased": 1,
        "barrel-aged": False,
    },
    {
        "name": "Garnet",
        "brewery": "Rye River",
        "year": 2019,
        "abv": 9.5,
        "style": "Imperial Brown",
        "size": 750,
        "drunk": False,
        "stock": 1,
        "purchased": 1,
        "barrel-aged": True,
        "barrel-type": "Cognac",
    },
    {
        "name": "The Helm of Awe",
        "brewery": "Sahtipaja",
        "year": 2018,
        "abv": 12.2,
        "style": "Imperial Stout",
        "size": 330,
        "drunk": False,
        "stock": 1,
        "purchased": 1,
        "barrel-aged": True,
        "barrel-type": "Red Wine",
        "brewed-with": "honey",
    },
    {
        "name": "Big Foot",
        "brewery": "Sierra Nevada",
        "year": 2011,
        "abv": 9.6,
        "style": "Barley Wine",
        "size": 355,
        "drunk": False,
        "stock": 1,
        "purchased": 1,
        "barrel-aged": False,
    },
    {
        "name": "Big Foot",
        "brewery": "Sierra Nevada",
        "year": 2012,
        "abv": 9.6,
        "style": "Barley Wine",
        "size": 355,
        "drunk": True,
        "stock": 1,
        "purchased": 1,
        "barrel-aged": False,
    },
    {
        "name": "Big Foot",
        "brewery": "Sierra Nevada",
        "year": 2013,
        "abv": 9.6,
        "style": "Barley Wine",
        "size": 355,
        "drunk": True,
        "stock": 1,
        "purchased": 1,
        "barrel-aged": False,
    },
    {
        "name": "Big Foot",
        "brewery": "Sierra Nevada",
        "year": 2014,
        "abv": 9.6,
        "style": "Barley Wine",
        "size": 355,
        "drunk": True,
        "stock": 1,
        "purchased": 1,
        "barrel-aged": False,
    },
    {
        "name": "Big Foot",
        "brewery": "Sierra Nevada",
        "year": 2015,
        "abv": 9.6,
        "style": "Barley Wine",
        "size": 355,
        "drunk": True,
        "stock": 1,
        "purchased": 1,
        "barrel-aged": False,
    },
    {
        "name": "Big Foot",
        "brewery": "Sierra Nevada",
        "year": 2016,
        "abv": 9.6,
        "style": "Barley Wine",
        "size": 355,
        "drunk": True,
        "stock": 1,
        "purchased": 1,
        "barrel-aged": False,
    },
    {
        "name": "Big Foot",
        "brewery": "Sierra Nevada",
        "year": 2016,
        "abv": 11.6,
        "style": "Barley Wine",
        "size": 710,
        "drunk": True,
        "stock": 1,
        "purchased": 1,
        "barrel-aged": True,
    },
    {
        "name": "Big Foot",
        "brewery": "Sierra Nevada",
        "year": 2017,
        "abv": 9.6,
        "style": "Barley Wine",
        "size": 355,
        "drunk": True,
        "stock": 1,
        "purchased": 1,
        "barrel-aged": False,
    },
    {
        "name": "Big Foot",
        "brewery": "Sierra Nevada",
        "year": 2018,
        "abv": 9.6,
        "style": "Barley Wine",
        "size": 355,
        "drunk": True,
        "stock": 1,
        "purchased": 1,
        "barrel-aged": False,
    },
    {
        "name": "Big Foot",
        "brewery": "Sierra Nevada",
        "year": 2019,
        "abv": 9.6,
        "style": "Barley Wine",
        "size": 355,
        "drunk": True,
        "stock": 1,
        "purchased": 1,
        "barrel-aged": False,
    },
    {
        "name": "Big Foot",
        "brewery": "Sierra Nevada",
        "year": 2020,
        "abv": 9.6,
        "style": "Barley Wine",
        "size": 355,
        "drunk": False,
        "stock": 2,
        "purchased": 2,
        "barrel-aged": False,
    },
    {
        "name": "40th Hoppy Anniversary Ale",
        "brewery": "Sierra Nevada",
        "year": 2020,
        "abv": 6,
        "style": "Hoppy Ale",
        "size": 355,
        "drunk": False,
        "stock": 1,
        "purchased": 1,
        "barrel-aged": False,
    },
    {
        "name": "Life And Limb",
        "brewery": "Sierra Nevada",
        "year": 2019,
        "abv": 10.2,
        "style": "Maple and Birch Syrup Ale",
        "size": 473,
        "drunk": True,
        "stock": 0,
        "purchased": 1,
        "barrel-aged": False,
    },
    {
        "name": "w00tstout",
        "brewery": "Stone",
        "year": 2018,
        "abv": 11.5,
        "style": "Stout",
        "size": 330,
        "drunk": False,
        "stock": 1,
        "purchased": 1,
        "barrel-aged": False,
    },
    {
        "name": "Old Fashined Bourbon Ale",
        "brewery": "Strathcona",
        "year": 2018,
        "abv": 7.5,
        "style": "Old Ale",
        "size": 650,
        "drunk": False,
        "stock": 1,
        "purchased": 1,
        "barrel-aged": False,
    },
    {
        "name": "Correctamundo",
        "brewery": "SuperFlux",
        "year": 2018,
        "abv": 7,
        "style": "Porter",
        "size": 473,
        "drunk": True,
        "stock": 0,
        "purchased": 1,
        "barrel-aged": False,
    },
    {
        "name": "Pretty Green",
        "brewery": "The Format",
        "year": 2019,
        "abv": 7.5,
        "style": "DDH IPA",
        "size": 440,
        "drunk": False,
        "stock": 1,
        "purchased": 1,
        "barrel-aged": False,
    },
    {
        "name": "The Darkness",
        "brewery": "Third Barrel",
        "year": 2019,
        "abv": 10,
        "style": "Baltic Porter",
        "size": 330,
        "drunk": True,
        "stock": 0,
        "purchased": 2,
        "ibu": 70,
        "barrel-aged": True,
    },
    {
        "name": "In to the Fucking Stratasphere",
        "brewery": "Third Barrel",
        "year": 2019,
        "abv": 11,
        "style": "Triple IPA",
        "size": 440,
        "drunk": True,
        "stock": 0,
        "purchased": 1,
        "barrel-aged": False,
    },
    {
        "name": "Westvleteren xii",
        "brewery": "Westvleteren",
        "year": 2014,
        "abv": 10.2,
        "style": "Trappist",
        "size": 330,
        "drunk": True,
        "stock": 1,
        "purchased": 1,
        "barrel-aged": True,
    },
    {
        "name": "Westvleteren xii",
        "brewery": "Westvleteren",
        "year": 2018,
        "abv": 10.2,
        "style": "Trappist",
        "size": 330,
        "drunk": True,
        "stock": 1,
        "purchased": 1,
        "barrel-aged": False,
    },
    {
        "name": "Olcan",
        "brewery": "White Hag",
        "year": 2017,
        "abv": 6,
        "style": "Brett IPA",
        "size": 375,
        "drunk": False,
        "stock": 1,
        "purchased": 1,
        "barrel-aged": True,
    },
    {
        "name": "Hagstravaganza 4 - Black Boar Barrel Aged With Raspberries",
        "brewery": "White Hag",
        "year": 2018,
        "abv": 11.6,
        "style": "Imperial Stout",
        "size": 750,
        "drunk": True,
        "stock": 1,
        "purchased": 1,
        "barrel-aged": True,
        "brewed-with": "raspberries",
    },
    {
        "name": "Hagstravaganza 5 - Single Barrel Bourbon Barley Wine",
        "brewery": "White Hag",
        "year": 2019,
        "abv": 13,
        "style": "Barley Wine",
        "size": 750,
        "drunk": True,
        "stock": 2,
        "purchased": 2,
        "barrel-aged": True,
        "barrel-type": "Bourbon",
    },
    {
        "name": "No. 40",
        "brewery": "White Hag",
        "year": 2019,
        "abv": 13,
        "style": "Rye Wine",
        "size": 330,
        "drunk": True,
        "stock": 1,
        "purchased": 2,
        "collaborators": ["Brew By Numbers"],
        "barrel-aged": True,
    },
    {
        "name": "The Last Stand",
        "brewery": "Yellow Belly",
        "year": 2019,
        "abv": 8.2,
        "style": "American Barley wine",
        "size": 330,
        "drunk": False,
        "stock": 1,
        "purchased": 1,
        "barrel-aged": False,
    },
]
