{
 "title": "Beer Inventory",
 "description": "A Demo dashboard to show off tagged metrics",
 "tags": [
  "demo",
  "events service"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 0 },
   "targets": [
    { "expr": "sum (beer_stock)" }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 0 },
   "targets": [
    { "expr": "sum(beer_purchased_total)" }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "sum(req_time_seconds_sum{method=\"GET\"})"
    }
   ]
  },
  {
   "title": "Purchases by beer and abv",
   "type": "bargauge",
   "gridPos": { "h": 40, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by (brewery, abv) (beer_purchased_total)",
     "legendFormat": "{{brewery}} {{abv}}%"
    }
   ]
  },
  {
   "title": "Brewery Stock",
   "type": "bargauge",
   "gridPos": { "h": 17, "w": 12, "x": 0, "y": 6 },
   "targets": [
    { "expr": "sum by (brewery) (beer_stock)", "legendFormat": "{{brewery}}" }
   ]
  },
  {
   "title": "Beer Style Stock",
   "type": "bargauge",
   "gridPos": { "h": 17, "w": 12, "x": 0, "y": 23 },
   "targets": [
    { "expr": "sum by (style) (beer_stock)", "legendFormat": "{{style}}" }
   ]
  },
  {
   "title": "Reponse Time /api/v1/beers/instock",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "histogram_quantile(1, sum(rate(req_time_seconds_bucket{endpoint=\"/api/v1/beers/instock\"}[1m])) by (le))"
    }
   ]
  },
  {
   "title": "Logs for /api/v1/events/active",
   "type": "logs",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 40 },
   "targets": [
    {
     "expr": "{compose_service=\"server\"} !~ \"http://(localhost|server):8000/(api/v1/healthz|metrics)\" |~ \"/api/v1/beers/instock\""
    }
   ]
  },
  {
   "title": "Reponse Time /api/v1/beers",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 49 },
   "targets": [
    {
     "expr": "histogram_quantile(1, sum(rate(req_time_seconds_bucket{endpoint=\"/api/v1/beers\"}[1m])) by (le))"
    }
   ]
  },
  {
   "title": "Logs for /api/v1/beers",
   "type": "logs",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 49 },
   "targets": [
    {
     "expr": "{compose_service=\"server\"} !~ \"http://(localhost|server):8000/(api/v1/healthz|metrics)\" |~ \"/api/v1/beers\""
    }
   ]
  },
  {
   "title": "Reponse Time /api/v1/beer/:id",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 58 },
   "targets": [
    {
     "expr": "histogram_quantile(1, sum(rate(req_time_seconds_bucket{endpoint=\"/api/v1/beer/:id\"}[1m])) by (le))"
    }
   ]
  },
  {
   "title": "Logs for /api/v1/beer/:id",
   "type": "logs",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 58 },
   "targets": [
    {
     "expr": "{compose_service=\"server\"} !~ \"http://(localhost|server):8000/(api/v1/healthz|metrics)\" |~ \"/api/v1/beer/[0-9a-zA-Z]\""
    }
   ]
  },
  {
   "title": "Error Logs",
   "type": "logs",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 67 },
   "targets": [
    {
     "expr": "{compose_service=\"server\"} !~ \"http://(localhost|server):8000/(api/v1/healthz|metrics)\" |~ \"error\""
    }
   ]
  }
 ]
}