{
 "title": "Event Service",
 "description": "A Demo dashboard to show off tagged metrics",
 "tags": [
  "demo",
  "events service"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "db_events_count{state=\"completed\"}",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "db_events_count{state=\"active\"}",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "db_events_count{state=\"scheduled\"}",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "expr": "sum(req_time_seconds_sum{method=\"GET\"})"
    }
   ]
  },
  {
   "title": "Reponse Time /api/events/active",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "histogram_quantile(1, sum(rate(req_time_seconds_bucket{endpoint=\"/api/v1/events/active\"}[1m])) by (le))"
    }
   ]
  },
  {
   "title": "Logs for /api/v1/events/active",
   "type": "logs",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "{compose_service=\"server\"} !~ \"http://(localhost|server):8000/(api/v1/healthz|metrics)\" |~ \"/api/v1/events/active\""
    }
   ]
  },
  {
   "title": "Reponse Time /api/events",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "histogram_quantile(1, sum(rate(req_time_seconds_bucket{endpoint=\"/api/v1/events\"}[1m])) by (le))"
    }
   ]
  },
  {
   "title": "Logs for /api/v1/events",
   "type": "logs",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 15 },
   "targets": [
    {
     "expr": "{compose_service=\"server\"} !~ \"http://(localhost|server):8000/(api/v1/healthz|metrics)\" |~ \"/api/v1/events\""
    }
   ]
  },
  {
   "title": "Reponse Time /api/event/:id",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "histogram_quantile(1, sum(rate(req_time_seconds_bucket{endpoint=\"/api/v1/event/:id\"}[1m])) by (le))"
    }
   ]
  },
  {
   "title": "Logs for /api/v1/event/:id",
   "type": "logs",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "{compose_service=\"server\"} !~ \"http://(localhost|server):8000/(api/v1/healthz|metrics)\" |~ \"/api/v1/event/[0-9a-zA-Z]\""
    }
   ]
  },
  {
   "title": "Error Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "{compose_service=\"server\"} !~ \"http://(localhost|server):8000/(api/v1/healthz|metrics)\" |~ \"error\""
    }
   ]
  }
 ]
}